### PR TITLE
Add two steering-committee images #23

### LINKED ISSUE #23: Missing Images on steering-committee
**Describe the bug**
Go to https://science.eclipse.org/about/steering-committee/ 

The last 2 images are missing. If we don't have the images, let's use the default gray image. If we do have them, we should add them.

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #23 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
If the users update their Gravatar, would it break this change? This looks like it would be brittle

**Comment by flora8984461** [comment]
> If the users update their Gravatar, would it break this change? This looks like it would be brittle

Is there a way that we can connect to the user profile image and no matter whether they change it's always up to date with the user profile image? If not I will just download the default avatar and the current image to put in static to use.

**Comment by flora8984461** [comment]
I just checked the image for Jay is updated on the site, should we still use default Gravatar or use his image on profile?  https://accounts.eclipse.org/users/jbillings

**Comment by flora8984461** [comment]
I put the image to /static/ instead of using the unstable link.

**Comment by chrisguindon** [comment]
@autumnfound This page is hard-coded!

We will revisit this in the future but for now, I am happy with simply fixing the broken links and picture!

**Pull request merged**
